server:
  port: 8092


spring:
  application:
    name: Tables-service
  docker:
    compose:
      enabled: true
      file: compose.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: sa
    password: secret
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/restaurant
    user: sa
    password: secret

application-description: Table service
application-version: v1
